"use client";

import { useMemo, useState } from "react";
import type { TeacherGradeEntryResponse, StaffGradeSheetResponse, ScreenQuery } from "@/utils/client";
import { saveTeacherGrades, saveTeacherWeight } from "@/utils/client";

export type GradeRow = { id: number; number: string; name: string; status: "在籍" | "休学"; attendance: number; attitude: number; assignment: number; score?: number | null; gradeLabel?: string | null };
export const calculateScore = (row: Pick<GradeRow, "attendance" | "attitude" | "assignment">, weights: readonly number[]) => Math.min(100, Math.max(0, Math.round((row.attendance * weights[0] + row.attitude * 10 * weights[1] + row.assignment * 10 * weights[2]) / 10)));
export const gradeLabel = (score: number) => score >= 90 ? "秀" : score >= 80 ? "優" : score >= 70 ? "良" : score >= 60 ? "可" : "不可";
export function GradePill({ score, label }: Readonly<{ score: number; label?: string | null }>) { const value = label ?? gradeLabel(score); return <span className={`grade-pill grade-${value}`}>{value}<b>{score}</b></span>; }

export function GradeTable({ rows, subject, yearLabel, termLabel }: Readonly<{ rows: readonly GradeRow[]; subject: string; yearLabel: string; termLabel: string }>) {
  return <div className="grade-table-wrap"><table className="grade-table"><thead><tr><th>ステータス</th><th>学籍番号</th><th>氏名</th><th>出席率</th><th>授業態度</th><th>課題</th><th>点数</th><th>評価</th></tr></thead><tbody>{rows.map((row) => { const score = row.score; return <tr key={row.id}><td><span className={`status ${row.status === "在籍" ? "attending" : "on-leave"}`}>{row.status}</span></td><td>{row.number}</td><td className="student-name">{row.name}</td><td>{row.attendance}%</td><td>{row.attitude}</td><td>{row.assignment}</td><td>{score == null ? "—" : `${score}点`}</td><td>{score == null ? "—" : <GradePill score={score} label={row.gradeLabel} />}</td></tr>; })}</tbody></table><p className="table-caption">{subject}・{yearLabel} {termLabel}の成績</p></div>;
}

type MobileSubject = { subjectName: string; attendance: number; attitude: number; assignment: number; score: number; gradeLabel?: string | null };
export function MobileGradeSheet({ title, student, subjects, yearLabel, termLabel }: Readonly<{ title: string; student: StaffGradeSheetResponse["student"]; subjects: readonly MobileSubject[]; yearLabel: string; termLabel: string }>) {
  return <section className="mobile-grade-sheet" aria-label="スマホ用成績表"><div className="sheet-topline"><span>{title}</span><span>{yearLabel} {termLabel}</span></div><div className="sheet-person"><div><small>学籍番号</small><strong>{student.studentNumber}</strong></div><div><small>氏名</small><strong>{student.name}</strong></div></div><div className="sheet-overview"><div><small>平均点</small><strong>{subjects.length ? Math.round(subjects.reduce((sum, row) => sum + row.score, 0) / subjects.length) : "—"}<span>点</span></strong></div><div><small>修得科目</small><strong>{subjects.length}<span>科目</span></strong></div></div><div className="sheet-table-wrap"><table className="sheet-table"><thead><tr><th>科目</th><th>出席率</th><th>授業態度</th><th>課題</th><th>点数</th><th>評価</th></tr></thead><tbody>{subjects.map((row) => <tr key={row.subjectName}><td>{row.subjectName}</td><td>{row.attendance}%</td><td>{row.attitude}</td><td>{row.assignment}</td><td>{row.score}</td><td><GradePill score={row.score} label={row.gradeLabel} /></td></tr>)}</tbody></table></div></section>;
}

function NumericInput({ value, onChange, min, max, label }: Readonly<{ value: number; onChange: (value: number) => void; min: number; max: number; label: string }>) { return <input aria-label={label} type="number" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} />; }

export function GradeEditor({ data, subjectId, query = {}, staff = false }: Readonly<{ data: TeacherGradeEntryResponse; subjectId: number; query?: ScreenQuery; staff?: boolean }>) {
  const initialRows = () => data.students.map(({ student, grade }) => ({ id: student.id, number: student.studentNumber, name: student.name, status: student.isAttending ? "在籍" as const : "休学" as const, attendance: grade?.attendance ?? 0, attitude: grade?.attitude ?? 1, assignment: grade?.assignment ?? 1 }));
  const [weights, setWeights] = useState([data.weight?.attendanceWeight ?? 0, data.weight?.attitudeWeight ?? 0, data.weight?.assignmentWeight ?? 0]);
  const [rows, setRows] = useState<GradeRow[]>(initialRows);
  const [message, setMessage] = useState("");
  const weightTotal = weights.reduce((total, value) => total + value, 0);
  const completeRows = rows.filter((row) => row.status === "在籍" && row.attendance > 0 && row.attitude > 0 && row.assignment > 0).length;
  const average = useMemo(() => { const active = rows.filter((row) => row.status === "在籍"); return active.length && weightTotal === 10 ? Math.round(active.reduce((sum, row) => sum + calculateScore(row, weights), 0) / active.length) : 0; }, [rows, weights, weightTotal]);
  const updateRow = (id: number, field: "attendance" | "attitude" | "assignment", value: number) => setRows((previous) => previous.map((row) => row.id === id ? { ...row, [field]: value } : row));
  const save = async () => { if (weightTotal !== 10) return setMessage("重みの合計を10にしてください。"); try { await saveTeacherGrades(subjectId, query, rows.filter((row) => row.status === "在籍").map((row) => ({ studentId: row.id, attendance: row.attendance, attitude: row.attitude, assignment: row.assignment }))); setMessage(staff ? "成績を保存しました。確定は成績確定画面から行ってください。" : "成績を保存しました。"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存に失敗しました"); } };
  const saveWeights = async (next: number[]) => { setWeights(next); try { await saveTeacherWeight(subjectId, query, { attendanceWeight: next[0], attitudeWeight: next[1], assignmentWeight: next[2] }); setMessage("重みを保存しました。"); } catch (error) { setMessage(error instanceof Error ? error.message : "重みの保存に失敗しました"); } };
  return <><section className="weight-panel"><div><span className="eyebrow">評価基準</span><h2>重みを設定</h2><p>3項目の合計が10になるように設定してください。</p></div><div className="weight-inputs">{[["出席率", 0], ["授業態度", 1], ["課題", 2]].map(([label, index]) => <label key={String(label)}>{label}<NumericInput label={`${label}の重み`} value={weights[Number(index)]} min={1} max={10} onChange={(value) => saveWeights(weights.map((weight, itemIndex) => itemIndex === Number(index) ? value : weight))} /></label>)}<strong className={weightTotal === 10 ? "weight-total valid" : "weight-total"}>合計 <b>{weightTotal}</b> / 10</strong></div></section><section className="spreadsheet-panel"><div className="spreadsheet-heading"><div><span className="eyebrow">{data.year.year}年度・{data.term.label}</span><h2>{data.subject.name}</h2></div><div className="entry-summary"><span>入力済み</span><strong>{completeRows}<small>/ {data.progress.total}名</small></strong><span>平均 {average}点</span></div></div><div className="editor-table-wrap"><table className="editor-table"><thead><tr><th>学籍番号</th><th>氏名</th><th>出席率 (0〜100)</th><th>授業態度 (1〜10)</th><th>課題 (1〜10)</th><th>点数</th><th>評価</th></tr></thead><tbody>{rows.map((row) => { const score = weightTotal === 10 ? calculateScore(row, weights) : null; const disabled = row.status === "休学"; return <tr key={row.id} className={disabled ? "inactive-row" : ""}><td>{row.number}</td><td><strong>{row.name}</strong><small>{row.status}</small></td><td><NumericInput label={`${row.name}の出席率`} value={row.attendance} min={0} max={100} onChange={(value) => updateRow(row.id, "attendance", value)} /></td><td><NumericInput label={`${row.name}の授業態度`} value={row.attitude} min={1} max={10} onChange={(value) => updateRow(row.id, "attitude", value)} /></td><td><NumericInput label={`${row.name}の課題`} value={row.assignment} min={1} max={10} onChange={(value) => updateRow(row.id, "assignment", value)} /></td><td>{disabled || score == null ? "—" : `${score}点`}</td><td>{disabled || score == null ? "—" : <GradePill score={score} />}</td></tr>; })}</tbody></table></div><div className="entry-footer"><p className={message ? "entry-message" : "entry-message hidden"} role="status">{message || "保存前に入力内容を確認してください。"}</p><button className="primary-button" type="button" onClick={save}>保存する</button></div></section></>;
}
