"use client";

import { useMemo, useState } from "react";
import { WeightModal } from "@/component/modals";
import type { TeacherGradeEntryResponse, ScreenQuery } from "@/utils/client";
import { saveTeacherGrades, saveTeacherWeight } from "@/utils/client";
import { GradePill } from "@/component/grade-ui";

export function TeacherMobileGradesScreen({ data }: Readonly<{ data: TeacherGradeEntryResponse }>) {
  return <main className="teacher-mobile-grades-page"><nav className="teacher-mobile-grades-breadcrumb" aria-label="パンくず"><a href="/teacher">ホーム</a><b>›</b><span>担当科目</span><b>›</b><strong>成績一覧</strong></nav><h1>科目・{data.subject.name}</h1><section className="teacher-mobile-grades-table-shell" aria-label={`${data.subject.name}の成績一覧`}><table className="teacher-mobile-grades-table"><thead><tr><th>ステータス</th><th>学籍</th><th>氏名</th><th>出席率<br />(〇〇%)</th><th>授業態度<br />(1~10)</th><th>課題<br />(1~10)</th><th>点数</th><th>評価</th></tr></thead><tbody>{data.students.map(({ student, grade, gradeLabel }) => <tr key={student.id}><td>{student.isAttending ? "在籍" : "休学"}</td><td>{student.studentNumber}</td><td>{student.name}</td><td>{grade ? `${grade.attendance}%` : "—"}</td><td>{grade?.attitude ?? "—"}</td><td>{grade?.assignment ?? "—"}</td><td>{grade?.score == null ? "—" : `${grade.score}点`}</td><td>{grade ? <GradePill score={grade.score} label={gradeLabel} /> : "—"}</td></tr>)}</tbody></table></section></main>;
}

export function TeacherGradesScreen({ data, query = {} }: Readonly<{ data: TeacherGradeEntryResponse; query?: ScreenQuery }>) {
  const [search, setSearch] = useState("");
  const [message, setMessage] = useState("");
  const [weights, setWeights] = useState([data.weight?.attendanceWeight ?? 0, data.weight?.attitudeWeight ?? 0, data.weight?.assignmentWeight ?? 0]);
  const [weightModalOpen, setWeightModalOpen] = useState(false);
  const rows = useMemo(() => data.students.filter(({ student }) => `${student.studentNumber}${student.name}`.includes(search)), [data.students, search]);
  const saveWeights = async (next: number[]) => { setWeights(next); try { await saveTeacherWeight(data.subject.id, query, { attendanceWeight: next[0], attitudeWeight: next[1], assignmentWeight: next[2] }); setMessage("重みを保存しました。"); } catch (error) { setMessage(error instanceof Error ? error.message : "重みの保存に失敗しました"); } };
  const save = async () => { try { await saveTeacherGrades(data.subject.id, query, rows.filter(({ student }) => student.isAttending).map(({ student, grade }) => ({ studentId: student.id, attendance: grade?.attendance ?? 0, attitude: grade?.attitude ?? 1, assignment: grade?.assignment ?? 1 }))); setMessage("保存しました。"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存に失敗しました"); } };
  return <main className="teacher-grades-page"><header className="teacher-grades-header"><nav className="teacher-grades-breadcrumb" aria-label="パンくず"><span>ホーム</span><b>›</b><span>担当科目</span><b>›</b><strong>成績一覧</strong></nav><h1>科目・{data.subject.name}</h1><button className="teacher-grade-metrics" type="button" onClick={() => setWeightModalOpen(true)} aria-label="評価基準を変更">{[["出席率", weights[0]], ["授業態度", weights[1]], ["課題", weights[2]]].map(([label, value]) => <div key={String(label)}><strong>{label}</strong><span>{value}</span></div>)}</button><label className="teacher-grade-search"><span aria-hidden="true" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="（学籍・氏名）" aria-label="学籍・氏名で検索" /></label></header><section className="teacher-grades-table-shell"><table className="teacher-grades-table"><thead><tr><th>ステータス</th><th>学籍</th><th>氏名</th><th>出席率(〇〇%)</th><th>授業態度(1~10)</th><th>課題(1~10)</th><th>点数</th><th>評価</th></tr></thead><tbody>{rows.map(({ student, grade, gradeLabel }) => <tr key={student.id}><td>{student.isAttending ? "在籍" : "休学"}</td><td>{student.studentNumber}</td><td>{student.name}</td><td>{grade ? `${grade.attendance}%` : "—"}</td><td>{grade?.attitude ?? "—"}</td><td>{grade?.assignment ?? "—"}</td><td>{grade?.score == null ? "—" : `${grade.score}点`}</td><td>{grade ? <GradePill score={grade.score} label={gradeLabel} /> : "—"}</td></tr>)}</tbody></table></section><div className="teacher-grades-actions"><button className="teacher-incomplete-button" type="button" onClick={() => setMessage(data.progress.missing ? `未入力の成績が${data.progress.missing}件あります。` : "未入力の成績はありません。")}>未入力チェック</button><button className="teacher-save-button" type="button" onClick={save}>保存</button></div>{message && <p className="teacher-grades-message" role="status">{message}</p>}{weightModalOpen && <WeightModal weights={weights} onConfirm={saveWeights} onClose={() => setWeightModalOpen(false)} />}</main>;
}
